services:
  db:
    image: postgres:18
    platform: 'linux/amd64'
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./.docker/.data/database/18/docker:/var/lib/postgresql/18/docker
    ports:
      - ${DATABASE_PORT_OUT}:5432

